/**
 * The authority runtime gate (R0-A): the SANCTIONED producer of `ef/anchor`
 * events. Every anchor declared through this service has its claimed
 * authority validated against the raw events it cites BEFORE the event is
 * appended — derived authority must terminate at raw authority roots
 * (user/system messages, tool results, procedural execution), never at
 * another derived anchor.
 *
 * @module dsh-epistemic-fold/anchor-service
 */

import { randomUUID } from 'node:crypto'
import { Session, SessionId } from '@deepseek-ai/dsh-session'
import type { Session as SessionType } from '@deepseek-ai/dsh-session'
import { canVerify, isAuthorityGrounded } from './authority.ts'
import type { AuthoritativeEventKind } from './authority.ts'
import type { Anchor, EventRef, FailureState } from './state.ts'

const AUTHORITATIVE_KINDS: ReadonlySet<string> = new Set([
  'user/message',
  'system/message',
  'tool/result',
  'assistant/message',
])

/**
 * Whether this host admits a plugin-owned session event durably.
 *
 * DSH's persistence read path refuses to reopen a log containing an event type
 * outside its known vocabulary unless the record carries the envelope's
 * `ignorable` marker. `Session.append` is the only writer, and on hosts that
 * ignore its options bag the marker is silently dropped — so an `ef/anchor`
 * append succeeds in memory and leaves the session unopenable after a restart.
 *
 * The check probes the envelope `append` actually returns rather than reading a
 * version number, because the capability is per-build rather than per-version
 * and a version table would go stale; `dsh-background-agents` probes the same
 * marker for the same reason.
 *
 * @returns whether an `ignorable`-marked plugin event survives `append`.
 */
export function hostAdmitsPluginEvents(): boolean {
  try {
    const probe = Session.create(SessionId(`ef-capability-probe-${randomUUID()}`))
    // The typed `append` accepts options only for surface event types, so the
    // probe widens the RECEIVER and keeps calling `append` as a member: pulling
    // the method into a variable would drop its receiver and throw, which the
    // catch below would then report as "unsupported host" for the wrong reason.
    const untyped = probe as unknown as {
      append(type: string, data: unknown, opts: unknown): { readonly ignorable?: unknown }
    }
    const appended = untyped.append(
      'ef/anchor',
      { op: 'retire', anchorId: 'capability-probe' },
      { ignorable: true },
    )
    return appended.ignorable === true
  } catch {
    // A host that rejects the options bag outright is no more usable than one
    // that drops it, and both mean the same thing here.
    return false
  }
}

/** Construction options for the anchor service. */
export interface AnchorServiceOptions {
  /**
   * Whether this deployment may write a plugin-owned durable session event.
   *
   * Defaults to `true` — the in-memory and test face, where nothing persists
   * the log. The plugin wires the real host capability
   * ({@link hostAdmitsPluginEvents}); a deployment that persists sessions on a
   * host without the marker would otherwise poison every log it writes.
   */
  readonly durableWritesAllowed?: () => boolean
}

/**
 * An anchor under construction. Identity is normally generated by the gate;
 * callers may supply an explicit `id` when a deterministic, externally
 * referenced identity is required (evaluation oracles, cross-system refs).
 */
export type AnchorDraft = Omit<Anchor, 'id' | 'lifecycle'> & { readonly id?: string }

export interface AnchorService {
  /** Validate the draft's authority grounding, then append `ef/anchor`. */
  declare(session: SessionType, draft: AnchorDraft): Anchor
  /**
   * Advance a failure to VERIFIED. The evidence refs are resolved against
   * the session log and must ALL be empirical/procedural raw events —
   * assistant prose can never verify (Evidence Overrides Narrative).
   */
  verifyFailure(session: SessionType, failureAnchorId: string, evidenceRefs: readonly EventRef[]): void
  /** Advance a failure through investigating/resolved. */
  transitionFailure(session: SessionType, failureAnchorId: string, failureState: Exclude<FailureState, 'verified'>): void
  /** Retire an anchor by id. */
  retire(session: SessionType, anchorId: string): void
}

/** Resolve the raw event kinds behind one anchor's source refs. */
function citedKinds(session: SessionType, refs: readonly EventRef[]): AuthoritativeEventKind[] {
  const kinds: AuthoritativeEventKind[] = []
  for (const ref of refs) {
    const kind = session.eventAt(ref.seq)?.type
    if (kind !== undefined && AUTHORITATIVE_KINDS.has(kind)) {
      kinds.push(kind as AuthoritativeEventKind)
    }
  }
  return kinds
}

/** Create the anchor service; one instance may serve many sessions. */
export function createAnchorService(options: AnchorServiceOptions = {}): AnchorService {
  const durableWritesAllowed = options.durableWritesAllowed ?? ((): boolean => true)

  /**
   * Refuse BEFORE the append rather than after it. The failure this prevents
   * is a log that writes cleanly and cannot be reopened, so an error raised
   * afterwards would be no error at all — the damage is already durable.
   */
  function assertDurableWriteAllowed(): void {
    if (durableWritesAllowed()) return
    throw new Error(
      'epistemic-fold: refusing to append `ef/anchor` — this DSH host cannot mark a plugin-owned session '
      + 'event `ignorable`, and the persistence read path refuses to reopen a log containing an unknown event '
      + 'type without that marker. The anchor would look durable and make the session unopenable after a '
      + 'restart. See README, "State ownership".',
    )
  }

  function declare(session: SessionType, draft: AnchorDraft): Anchor {
    assertDurableWriteAllowed()
    const kinds = citedKinds(session, draft.sourceRefs)
    if (kinds.length === 0) {
      throw new Error(
        `epistemic-fold: ungrounded anchor — cite at least one raw authoritative event (kind=${draft.kind})`,
      )
    }
    if (!isAuthorityGrounded(draft.authority, kinds)) {
      throw new Error(
        `epistemic-fold: anchor authority "${draft.authority}" is not grounded by its cited sources `
        + `[${kinds.join(', ')}] (kind=${draft.kind})`,
      )
    }
    const anchor: Anchor = {
      ...draft,
      id: draft.id ?? `anchor-${randomUUID()}`,
      lifecycle: 'active',
    }
    session.append('ef/anchor', { op: 'declare', anchor })
    return anchor
  }

  function verifyFailure(session: SessionType, failureAnchorId: string, evidenceRefs: readonly EventRef[]): void {
    assertDurableWriteAllowed()
    if (evidenceRefs.length === 0) {
      throw new Error('epistemic-fold: VERIFIED requires at least one evidence ref')
    }
    const kinds = citedKinds(session, evidenceRefs)
    if (!canVerify(kinds)) {
      throw new Error(
        `epistemic-fold: VERIFIED refused — evidence kinds [${kinds.join(', ') || 'none'}] `
        + 'are not all empirical/procedural (Evidence Overrides Narrative)',
      )
    }
    session.append('ef/anchor', {
      op: 'transition',
      anchorId: failureAnchorId,
      failureState: 'verified',
      evidenceRefs: [...evidenceRefs],
    })
  }

  function transitionFailure(session: SessionType, failureAnchorId: string, failureState: Exclude<FailureState, 'verified'>): void {
    assertDurableWriteAllowed()
    session.append('ef/anchor', {
      op: 'transition',
      anchorId: failureAnchorId,
      failureState,
    })
  }

  function retire(session: SessionType, anchorId: string): void {
    assertDurableWriteAllowed()
    session.append('ef/anchor', { op: 'retire', anchorId })
  }

  return { declare, verifyFailure, transitionFailure, retire }
}
